### ISSUE TITLE
Only build once

### ISSUE THREAD

**Issue by ShaoYongChao** [marcelocorreia/mcduino#2]
Only build once,then "Command exited","Command killed with signal GTERM",must Reload ide.

**Comment by marcelocorreia** [comment]
Hi there,
Can you please provide some more details? 
cheers

**Comment by marcelocorreia** [comment]
Not able to replicate issue, closing down due to lack of feedback

**Comment by ReeSilva** [comment]
Im having the same issue. There isnt much details to give. On Fedora 22, my OS, u run any command of the mcduino and when u try to run again it returnos Command killed with signal SIGTERM

**Comment by jango-fx** [comment]
same Problem on 
OS X 10.10.5
Arduino IDE 1.06
Arduino Uno
ano 0.4.5

no matter if use `ino` or `ano`, if i run any command (e.g. `build`, `upload`) once via the mcduino-toolbar, it works fine. However I get

```
Command exited
```

at the end. And then have to reload the IDE (or restart Atom) or I'll get:

```
Command killed with signal SIGTERM
```

Everything works fine via Terminal.

**Comment by cjwiet** [comment]
I am having the same issue. The feedback provided above is pretty much exactly the same issue I'm having. In order to run any command after I've already run a command, I have to "reload" Atom. It seems as if after one command is finished running, all subsequent commands are perpetually killed with SIGTERM before they can even begin to execute.

**Comment by cjwiet** [comment]
I appear to have prevented the constant killing by commenting out line 46 in command-runner.coffee, but I don't have a great grasp of what the code is really doing, so I highly doubt this is a good solution to the problem.
